# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: set environment variables
      uses: allenevans/set-env@v2.0.0
      with:
          OHOS_SDK_HOME: ${GITHUB_WORKSPACE}

    - name: Printenv
      run: |
           echo "OHOS_SDK_HOME=${OHOS_SDK_HOME}"
           printenv
    - name: directory
      run: echo %cd%
    - name: environment
      run: set OHOS_SDK_HOME=%cd%/huawei
    - name: Build with Gradle
      run: ./gradlew build
